# Generated by Django 2.2.7 on 2019-11-27 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailapp', '0002_userprofileinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='indicesList',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='portfolio_site',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='profile_pic',
        ),
    ]
