# Generated by Django 2.2.7 on 2019-11-27 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailapp', '0003_auto_20191127_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='userPubKey',
            field=models.CharField(default='xxxxxxxxxx', max_length=1000),
            preserve_default=False,
        ),
    ]
