# Generated by Django 2.2.7 on 2019-11-27 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailapp', '0005_auto_20191127_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionkeysenc',
            name='keyEncA',
            field=models.TextField(default='xxxxxxxxxx'),
        ),
        migrations.AlterField(
            model_name='sessionkeysenc',
            name='keyEncB',
            field=models.TextField(default='xxxxxxxxxx'),
        ),
        migrations.AlterField(
            model_name='sessionkeysenc',
            name='userA',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sessionkeysenc',
            name='userB',
            field=models.CharField(max_length=100),
        ),
    ]
