# Generated by Django 2.2.7 on 2019-11-27 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailapp', '0006_auto_20191127_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='userPubKey',
            field=models.CharField(default='xxxxxxxxxx', max_length=1000),
        ),
    ]
