# Generated by Django 2.2.7 on 2019-11-28 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailapp', '0008_userprofileinfo_userprivkey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='userPrivKey',
        ),
    ]
